services:
  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${STORAGE}/config/nginx-config/data:/data
      - ${STORAGE}/config/nginx-config/etc:/etc/letsencrypt
